server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /openai-api/ {
        proxy_pass https://s2a.shuai.help/v1/;
        proxy_ssl_server_name on;
        proxy_set_header Host s2a.shuai.help;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /gemini-api/ {
        proxy_pass https://s2a.shuai.help/v1/;
        proxy_ssl_server_name on;
        proxy_set_header Host s2a.shuai.help;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /nvidia-api/ {
        proxy_pass https://integrate.api.nvidia.com/v1/;
        proxy_ssl_server_name on;
        proxy_set_header Host integrate.api.nvidia.com;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /grok-api/ {
        proxy_pass http://43.155.204.215:18000/v1/;
        proxy_set_header Host 43.155.204.215;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
